services:
  #Db
  promocode-factory-db:
    image: "postgres:latest"
    container_name: 'promocode-factory-db'
    restart: always 
    ports:
      - 5433:5432
    environment: 
      - POSTGRES_PASSWORD=docker
      - PGDATA=/data/postgres
      - POSTGRES_DB=promocode-factory-db
    volumes:
      - db:/data/postgres    

  #Api
  promocode-factory-api:
#    build: src
    image: "m1skipper/edu:latest"
    container_name: 'promocode-factory-api'
    restart: always
    ports:
      - "5000:8080"
    environment:
      - "ConnectionStrings:PromoCodeFactoryDb=Host=promocode-factory-db;Database=promocode-factory-db;Username=postgres;Password=docker"          
    depends_on: 
      - promocode-factory-db

  #PgAdmin
#  pgadmin:
#    image: dpage/pgadmin4:latest
#    hostname: pgadmin
#    restart: always
#    environment: 
#      PGADMIN_DEFAULT_EMAIL: admin@m.ru
#      PGADMIN_DEFAULT_PASSWORD: 1
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
#    ports:
#      - "5050:80"

volumes:
  db:
#  pgadmin-data:
