name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildAndTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Homeworks/UnitTests/src
    - name: Build
      run: dotnet build --no-restore
      working-directory: Homeworks/UnitTests/src
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Homeworks/UnitTests/src

  buildDockerAndPublish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ./Homeworks/UnitTests/src
        push: true
        tags: m1skipper/edu:latest

    - name: Run Docker Compose
      run: docker compose -f ./Homeworks/UnitTests/compose.yml up -d
